language: php
php:
  - 7.1
before_script:
  - composer install
  - cd public/
  - php -S 0.0.0.0:8888 &
script:
  - cd ../
  - ./vendor/bin/phpcs -n --standard=phpcs.xml
  - ./vendor/bin/phpmd app text phpmd.xml
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/