language: php
php:
  - 7.1
before_script:
  - composer install
script:
  - ./vendor/bin/phpcs -n --standard=phpcs.xml
  - ./vendor/bin/phpmd app text phpmd.xml
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/